export * from './tipos'
export * from './componentes'
export { resolver, claveNodo, type Solucion } from './solver'
export { Motor, DT_POR_DEFECTO, type EventoSimulacion } from './motor'
export { validarCircuito } from './validacion'
